/* Generated by Kapila Compiler */
#include "kapila.h"

/* === User-defined words === */

void word_ವರ_ccd_ಗ(void) {
    dup_op();
    mul_op();
}

int main() {
    kapila_init();
    
    push_int(5);
    push_int(3);
    add_op();
    println_op();
    push_int(10);
    push_int(4);
    sub_op();
    println_op();
    push_int(6);
    push_int(7);
    mul_op();
    println_op();
    push_int(5);
    word_ವರ_ccd_ಗ();
    println_op();
    push_str("ನಮಸ್ಕಾರ ಪ್ರಪಂಚ!");
    println_op();
    
    kapila_cleanup();
    return 0;
}